### ISSUE TITLE
Database script mll_site.sql does not work on a mac

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Site#1]
please do a fresh export. the alter statements do not work on a MAC

**Comment by simon-begin** [comment]
https://github.com/MaisonLogicielLibre/Site/commit/0a39732536b7587b8bc7929ba3318b37883a2f68

A essayer si le problème est regler

**Comment by appliedrd** [comment]
will try it this afternoon

**Comment by appliedrd** [comment]
works with phpmyadmin - not mysql workbench. must be a version issue on my mac.

**Comment by appliedrd** [comment]
switch form mysql workbench to phpmyadmin on the mac. works. so bug in workbench - for mac.
